### ISSUE TITLE
[Refactor] 신원 인증 - 관리자 확인 용

### ISSUE THREAD

**Issue by INUK-ai** [MTVS3FinalProject/MTVS3_Final_BackEnd#70]
# ✅기능 이슈

## Description

> 신원 인증을 관리자가 확인하는 것으로 변경

<br>

## To Do

- [ ] 관리자용 QR 생성
- [ ] 신원 인증 - 관리자 화면에서
- [ ] 티켓 확인

<br>

## ETC

> 기타사항

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified QRCommandService and QRController to add admin QR generation and verification functionality. Removed automatic verification and added admin-based verification process.

You can review changes in this commit: https://github.com/mnmnk43434/MTVS3FinalProject-MTVS3_Final_BackEnd-70/commit/edfd2ad120908730c1f53163c0519c42ff53a3f1.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
